export const membersData = [
  {
    email: "lisa@test.com",
    username: "lisa",
    gender: "female",
    dateOfBirth: "1986-07-22",
    name: "ליסה",
    created: "2020-06-24",
    lastActive: "2020-06-21",
    description:
      "אני אוהבת לבלות זמן בטבע, לטייל ולחוות חוויות חדשות. אני מחפשת אדם עם תחומי עניין דומים, שיודע להעריך את החיים ואת הקטנים שבדברים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f1.jpeg",
  },
  {
    email: "karen@test.com",
    username: "karen",
    gender: "female",
    dateOfBirth: "1995-10-12",
    name: "קרן",
    created: "2019-12-09",
    lastActive: "2020-05-06",
    description:
      "אוהבת לצחוק, לשוחח ולהכיר אנשים חדשים. חשוב לי שמישהו יוכל להבין אותי ויתקשר בצורה כנה וישירה. מחפשת קשר אמיתי ומשמעותי.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f2.jpeg",
  },
  {
    email: "margo@test.com",
    username: "margo",
    gender: "female",
    dateOfBirth: "1989-01-24",
    name: "מרגו",
    created: "2019-08-10",
    lastActive: "2020-05-12",
    description:
      "אני אוהבת לבלות עם חברים, לשתות קפה טוב ולהאזין למוזיקה. מחפשת מישהו שיאהב לחלוק חוויות משותפות וילך איתי לטיולים ספונטניים.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/f3.jpeg",
  },
  {
    email: "lois@test.com",
    username: "lois",
    gender: "female",
    dateOfBirth: "1988-06-22",
    name: "לואיס",
    created: "2019-04-24",
    lastActive: "2020-06-17",
    description:
      "אוהבת לגלות מקומות חדשים ולפגוש אנשים עם תחומי עניין דומים. מחפשת מישהו שיכול להעניק לי את הזמן והמרחב להיות אני.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/f4.jpeg",
  },
  {
    email: "ruthie@test.com",
    username: "ruthie",
    gender: "female",
    dateOfBirth: "1986-01-12",
    name: "רותי",
    created: "2019-04-30",
    lastActive: "2020-06-21",
    description:
      "אני אוהבת לעזור לאנשים וליצור קשרים אמיתיים. מחפשת אדם פתוח, חייכן ועם חוש הומור טוב. בוא נגלה יחד את העולם.",
    city: "אילת",
    country: "ישראל",
    image: "/images/f5.jpeg",
  },
  {
    email: "todd@test.com",
    username: "todd",
    gender: "male",
    dateOfBirth: "1980-02-07",
    name: "טוד",
    created: "2019-04-29",
    lastActive: "2020-05-16",
    description:
      "אני אדם אוהב חיים, עם תחביבים מגוונים. חשוב לי להכיר מישהי כנה שתוכל לחלוק איתי חוויות ולצחוק ביחד.",
    city: "רמת גן",
    country: "ישראל",
    image: "/images/m1.jpeg",
  },
  {
    email: "porter@test.com",
    username: "porter",
    gender: "male",
    dateOfBirth: "1997-04-09",
    name: "פורטור",
    created: "2020-04-05",
    lastActive: "2020-06-23",
    description:
      "אני אדם עם תחומי עניין מגוונים. אוהב לטייל ולפגוש אנשים חדשים. מחפש מישהי שיכולה להיות החברה הכי טובה שלי ולהיות מישהי שאני יכול לסמוך עליה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m2.jpeg",
  },
  {
    email: "mayo@test.com",
    username: "mayo",
    gender: "male",
    dateOfBirth: "1990-03-23",
    name: "מאיו",
    created: "2020-03-14",
    lastActive: "2020-05-17",
    description:
      "אני אוהב אתגרים וחדשנות, ותמיד פתוח ללמוד ולהתפתח. מחפש מישהו עם מחשבה פתוחה ומעניין אותי לגלות איתו עולם חדש.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/m3.jpeg",
  },
  {
    email: "skinner@test.com",
    username: "skinner",
    gender: "male",
    dateOfBirth: "1982-12-01",
    name: "סקינר",
    created: "2019-01-28",
    lastActive: "2020-06-07",
    description:
      "אני אדם חייכן, אוהב להכיר אנשים חדשים ולנסות דברים חדשים. מחפש קשר רציני ומעוניין להכיר מישהי עם תחומי עניין דומים.",
    city: "חולון",
    country: "ישראל",
    image: "/images/m4.jpeg",
  },
  {
    email: "davis@test.com",
    username: "davis",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "avis",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "אני אדם פשוט שאוהב לבלות עם חברים, לראות סרטים ולשוחח על נושאים מעניינים. מחפש מישהי שמחפשת קשר אמיתי וישיר.",
    city: "אשדוד",
    country: "ישראל",
    image: "/images/m5.jpeg",
  },
  {
    email: "almayo@test.com",
    username: "almayo",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "אלמאיו",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "אני אוהב את החיים, מוזיקה טובה, טיולים ויצירת קשרים אמיתיים. מחפש מישהי כנה עם תחומי עניין משותפים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/almayo.jpg",
  },
];
