export const membersData = [
  {
    email: "fasika@test.com",
    username: "fasika",
    gender: "female",
    dateOfBirth: "1998-04-09",
    name: "פסיקה",
    created: "2025-01-15",
    lastActive: "2025-01-15",
    description:
      "סטודנטית למשפטים עם תשוקה לצדק ולעולם המשפט. אני חיה בין ספרי החוקים לאודיטוריום, אבל מחפשת מישהו לחלוק איתו רגעים פשוטים.",
    city: "מעלה אדומים",
    country: "ישראל",
    image: "/images/f11.jpg",
  },
  {
    email: "lisa@test.com",
    username: "lisa",
    gender: "female",
    dateOfBirth: "1986-07-22",
    name: "ליסה",
    created: "2020-06-24",
    lastActive: "2020-06-21",
    description:
      "אני אוהבת לבלות זמן בטבע, לטייל ולחוות חוויות חדשות. אני מחפשת אדם עם תחומי עניין דומים, שיודע להעריך את החיים ואת הקטנים שבדברים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f1.jpg",
  },
  {
    email: "karen@test.com",
    username: "karen",
    gender: "female",
    dateOfBirth: "1995-10-12",
    name: "קרן",
    created: "2019-12-09",
    lastActive: "2020-05-06",
    description:
      "אוהבת לצחוק, לשוחח ולהכיר אנשים חדשים. חשוב לי שמישהו יוכל להבין אותי ויתקשר בצורה כנה וישירה. מחפשת קשר אמיתי ומשמעותי.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f2.jpg",
  },
  {
    email: "margo@test.com",
    username: "margo",
    gender: "female",
    dateOfBirth: "1989-01-24",
    name: "מרגו",
    created: "2019-08-10",
    lastActive: "2020-05-12",
    description:
      "אני אוהבת לבלות עם חברים, לשתות קפה טוב ולהאזין למוזיקה. מחפשת מישהו שיאהב לחלוק חוויות משותפות וילך איתי לטיולים ספונטניים.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/f3.jpg",
  },
  {
    email: "lois@test.com",
    username: "lois",
    gender: "female",
    dateOfBirth: "1988-06-22",
    name: "לואיס",
    created: "2019-04-24",
    lastActive: "2020-06-17",
    description:
      "אוהבת לגלות מקומות חדשים ולפגוש אנשים עם תחומי עניין דומים. מחפשת מישהו שיכול להעניק לי את הזמן והמרחב להיות אני.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/f4.jpg",
  },
  {
    email: "ruthie@test.com",
    username: "ruthie",
    gender: "female",
    dateOfBirth: "1986-01-12",
    name: "רותי",
    created: "2019-04-30",
    lastActive: "2020-06-21",
    description:
      "אני אוהבת לעזור לאנשים וליצור קשרים אמיתיים. מחפשת אדם פתוח, חייכן ועם חוש הומור טוב. בוא נגלה יחד את העולם.",
    city: "אילת",
    country: "ישראל",
    image: "/images/f5.jpg",
  },
  {
    email: "todd@test.com",
    username: "todd",
    gender: "male",
    dateOfBirth: "1980-02-07",
    name: "טוד",
    created: "2019-04-29",
    lastActive: "2020-05-16",
    description:
      "אני אדם אוהב חיים, עם תחביבים מגוונים. חשוב לי להכיר מישהי כנה שתוכל לחלוק איתי חוויות ולצחוק ביחד.",
    city: "רמת גן",
    country: "ישראל",
    image: "/images/m1.jpg",
  },
  {
    email: "porter@test.com",
    username: "porter",
    gender: "male",
    dateOfBirth: "1997-04-09",
    name: "פורטור",
    created: "2020-04-05",
    lastActive: "2020-06-23",
    description:
      "אני אדם עם תחומי עניין מגוונים. אוהב לטייל ולפגוש אנשים חדשים. מחפש מישהי שיכולה להיות החברה הכי טובה שלי ולהיות מישהי שאני יכול לסמוך עליה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m2.jpg",
  },
  {
    email: "mayo@test.com",
    username: "mayo",
    gender: "male",
    dateOfBirth: "1990-03-23",
    name: "מאיו",
    created: "2020-03-14",
    lastActive: "2020-05-17",
    description:
      "אני אוהב אתגרים וחדשנות, ותמיד פתוח ללמוד ולהתפתח. מחפש מישהו עם מחשבה פתוחה ומעניין אותי לגלות איתו עולם חדש.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/m3.jpg",
  },
  {
    email: "skinner@test.com",
    username: "skinner",
    gender: "male",
    dateOfBirth: "1982-12-01",
    name: "סקינר",
    created: "2019-01-28",
    lastActive: "2020-06-07",
    description:
      "אני אדם חייכן, אוהב להכיר אנשים חדשים ולנסות דברים חדשים. מחפש קשר רציני ומעוניין להכיר מישהי עם תחומי עניין דומים.",
    city: "חולון",
    country: "ישראל",
    image: "/images/m4.jpg",
  },
  {
    email: "davis@test.com",
    username: "davis",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "avis",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "אני אדם פשוט שאוהב לבלות עם חברים, לראות סרטים ולשוחח על נושאים מעניינים. מחפש מישהי שמחפשת קשר אמיתי וישיר.",
    city: "אשדוד",
    country: "ישראל",
    image: "/images/m5.jpg",
  },
  {
    email: "almayo@test.com",
    username: "almayo",
    gender: "male",
    dateOfBirth: "1978-03-20",
    name: "אלמאיו",
    created: "2020-02-25",
    lastActive: "2020-06-11",
    description:
      "אני אוהב את החיים, מוזיקה טובה, טיולים ויצירת קשרים אמיתיים. מחפש מישהי כנה עם תחומי עניין משותפים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/almayo.jpg",
  },

  //////////////////////
  {
    email: "sara@test.com",
    username: "sara",
    gender: "female",
    dateOfBirth: "1992-07-15",
    name: "שרה",
    created: "2020-07-10",
    lastActive: "2020-06-22",
    description:
      "אני אוהבת ספורט, מוזיקה ואומנות. מחפשת מישהו שיאהב את החיים ויתמוך בי גם ברגעים הפחות מושלמים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f6.jpg",
  },
  {
    email: "dina@test.com",
    username: "dina",
    gender: "female",
    dateOfBirth: "1994-02-05",
    name: "דינה",
    created: "2020-05-01",
    lastActive: "2020-06-19",
    description:
      "אני אוהבת לטייל ולפגוש אנשים חדשים. מחפשת קשר שבו יהיה אפשר לדבר בכנות על הכל.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/f7.jpg",
  },
  {
    email: "noa@test.com",
    username: "noa",
    gender: "female",
    dateOfBirth: "1987-11-30",
    name: "נועה",
    created: "2020-03-22",
    lastActive: "2020-06-15",
    description:
      "אני אוהבת לרקוד ולבשל. מחפשת קשר כנה ויציב עם מישהו שאוהב את החיים.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/f8.jpg",
  },
  {
    email: "tamar@test.com",
    username: "tamar",
    gender: "female",
    dateOfBirth: "1990-09-18",
    name: "תמר",
    created: "2020-01-10",
    lastActive: "2020-06-13",
    description:
      "אני נהניתי מלימודים ומטבע. מחפשת מישהו שיהיה חבר אמיתי ויכלול אותי בחוויותיו.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/f9.jpg",
  },
  {
    email: "maya@test.com",
    username: "maya",
    gender: "female",
    dateOfBirth: "1993-03-11",
    name: "מאיה",
    created: "2020-04-20",
    lastActive: "2020-06-23",
    description:
      "אני אוהבת לקרוא ספרים ולצאת לטיולים בטבע. מחפשת קשר שיהיה אמיתי וכנה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f10.jpg",
  },
  {
    email: "lior@test.com",
    username: "lior",
    gender: "male",
    dateOfBirth: "1992-08-25",
    name: "ליאור",
    created: "2020-03-05",
    lastActive: "2020-06-18",
    description:
      "אני אוהב ספורט, טיולים, ושיחות מעניינות. מחפש מישהי שיהיה לה תחומי עניין דומים.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m6.webp",
  },
  {
    email: "gal@test.com",
    username: "gal",
    gender: "male",
    dateOfBirth: "1990-01-14",
    name: "גל",
    created: "2019-12-22",
    lastActive: "2020-06-12",
    description:
      "אני אוהב לטייל ולגלות מקומות חדשים. מחפש מישהי שמחפשת קשר אמיתי ומיוחד.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/m7.jpeg",
  },
  {
    email: "adam@test.com",
    username: "adam",
    gender: "male",
    dateOfBirth: "1985-04-17",
    name: "אדם",
    created: "2019-10-30",
    lastActive: "2020-06-20",
    description:
      "אני אוהב ספורט אתגרי, מוזיקה והרבה בילויים עם חברים. מחפש מישהי פתוחה, חייכנית ומוכנה ללמוד יחד.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/m8.avif",
  },
  {
    email: "idan@test.com",
    username: "idan",
    gender: "male",
    dateOfBirth: "1994-12-30",
    name: "עידן",
    created: "2020-02-10",
    lastActive: "2020-06-24",
    description:
      "אני אדם רגיש ואכפתי, אוהב לקרוא ולפגוש אנשים חדשים. מחפש קשר שיהיה אמיתי ומרגש.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m9.jpg",
  },
  {
    email: "ori@test.com",
    username: "ori",
    gender: "male",
    dateOfBirth: "1988-07-02",
    name: "אורי",
    created: "2020-01-05",
    lastActive: "2020-06-09",
    description:
      "אני אוהב אתגרים ולטפח תחביבים חדשים. מחפש מישהי שתהיה חברה אמיתית ותומכת.",
    city: "חולון",
    country: "ישראל",
    image: "/images/m10.jpg",
  },
  // New female users (f12-f24)
  {
    email: "shani@test.com",
    username: "shani",
    gender: "female",
    dateOfBirth: "1991-05-18",
    name: "שני",
    created: "2020-08-15",
    lastActive: "2026-01-12",
    description:
      "אני אוהבת אמנות, צילום ויוגה. מחפשת מישהו שיודע להעריך את היופי בדברים הקטנים ואוהב לחיות את הרגע.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f12.jpg",
  },
  {
    email: "yael@test.com",
    username: "yael",
    gender: "female",
    dateOfBirth: "1996-09-22",
    name: "יעל",
    created: "2020-09-01",
    lastActive: "2026-01-13",
    description:
      "סטודנטית לעיצוב גרפי, אוהבת קפה, ספרים טובים וטיולים בטבע. מחפשת מישהו עם תשוקה לחיים וחוש הומור.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/f13.jpg",
  },
  {
    email: "chen@test.com",
    username: "chen",
    gender: "female",
    dateOfBirth: "1989-12-10",
    name: "חן",
    created: "2020-09-20",
    lastActive: "2026-01-11",
    description:
      "מורה לאנגלית עם אהבה למוזיקה ולתרבות. אוהבת לבשל, לצחוק ולהכיר אנשים מעניינים. מחפשת קשר עמוק ואותנטי.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/f14.jpg",
  },
  {
    email: "roni@test.com",
    username: "roni",
    gender: "female",
    dateOfBirth: "1993-03-28",
    name: "רוני",
    created: "2020-10-05",
    lastActive: "2026-01-14",
    description:
      "אני אוהבת ים, שקיעות ואנשים אמיתיים. עובדת בתחום ההיי-טק ומחפשת איזון בין קריירה לאהבה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f15.jpg",
  },
  {
    email: "merav@test.com",
    username: "merav",
    gender: "female",
    dateOfBirth: "1987-07-14",
    name: "מירב",
    created: "2020-10-20",
    lastActive: "2026-01-12",
    description:
      "פסיכולוגית עם תשוקה להבנת האדם. אוהבת תיאטרון, סרטים ושיחות עמוקות. מחפשת מישהו בוגר ורגשית.",
    city: "רמת גן",
    country: "ישראל",
    image: "/images/f16.jpg",
  },
  {
    email: "hila@test.com",
    username: "hila",
    gender: "female",
    dateOfBirth: "1995-01-03",
    name: "הילה",
    created: "2020-11-01",
    lastActive: "2026-01-13",
    description:
      "אוהבת לרקוד, לטייל ולגלות מסעדות חדשות. מחפשת מישהו שאוהב הרפתקאות ויודע ליהנות מהחיים.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/f17.jpg",
  },
  {
    email: "dana@test.com",
    username: "dana",
    gender: "female",
    dateOfBirth: "1992-11-25",
    name: "דנה",
    created: "2020-11-15",
    lastActive: "2026-01-11",
    description:
      "מהנדסת תוכנה עם אהבה לפאזלים, משחקים ומדע בדיוני. מחפשת מישהו חכם עם חוש הומור ייחודי.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f18.jpg",
  },
  {
    email: "shira@test.com",
    username: "shira",
    gender: "female",
    dateOfBirth: "1990-08-07",
    name: "שירה",
    created: "2020-12-01",
    lastActive: "2026-01-14",
    description:
      "זמרת ומורה למוזיקה. אני חיה את המוזיקה וחושבת שהיא יכולה לבטא הכל. מחפשת מישהו שיצור איתי הרמוניה.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/f19.jpg",
  },
  {
    email: "adi@test.com",
    username: "adi",
    gender: "female",
    dateOfBirth: "1994-04-19",
    name: "עדי",
    created: "2020-12-10",
    lastActive: "2026-01-12",
    description:
      "אני אוהבת כושר, בריאות ואורח חיים פעיל. מחפשת מישהו שגם אוהב לשמור על עצמו ומעוניין בקשר בריא.",
    city: "אילת",
    country: "ישראל",
    image: "/images/f20.jpg",
  },
  {
    email: "karin@test.com",
    username: "karin",
    gender: "female",
    dateOfBirth: "1988-10-30",
    name: "קרין",
    created: "2021-01-05",
    lastActive: "2026-01-13",
    description:
      "רופאה וטרינרית עם אהבה עצומה לחיות. אני מטפלת, רגישה ואכפתית. מחפשת מישהו שגם אוהב בעלי חיים.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/f21.jpg",
  },
  {
    email: "sigal@test.com",
    username: "sigal",
    gender: "female",
    dateOfBirth: "1991-02-14",
    name: "סיגל",
    created: "2021-01-20",
    lastActive: "2026-01-11",
    description:
      "מעצבת פנים עם עין לפרטים. אוהבת יצירה, אסתטיקה ודברים יפים. מחפשת קשר שייתן לי השראה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/f22.jpg",
  },
  {
    email: "efrat@test.com",
    username: "efrat",
    gender: "female",
    dateOfBirth: "1997-06-08",
    name: "אפרת",
    created: "2021-02-01",
    lastActive: "2026-01-14",
    description:
      "סטודנטית לתקשורת עם תשוקה לכתיבה וסיפורים. אני סקרנית, אוהבת ללמוד ולגלות דברים חדשים.",
    city: "חולון",
    country: "ישראל",
    image: "/images/f23.jpg",
  },
  {
    email: "liat@test.com",
    username: "liat",
    gender: "female",
    dateOfBirth: "1986-09-16",
    name: "ליאת",
    created: "2021-02-15",
    lastActive: "2026-01-12",
    description:
      "עורכת דין בתחום זכויות האדם. אני נלחמת למען צדק ואמונה בשינוי. מחפשת מישהו עם ערכים דומים ולב גדול.",
    city: "אשדוד",
    country: "ישראל",
    image: "/images/f24.jpg",
  },
  // New male users (m11-m25)
  {
    email: "amir@test.com",
    username: "amir",
    gender: "male",
    dateOfBirth: "1990-03-12",
    name: "אמיר",
    created: "2020-08-10",
    lastActive: "2026-01-13",
    description:
      "מפתח תוכנה עם אהבה לטכנולוגיה וחדשנות. אוהב טיולים, קפה טוב ושיחות מעניינות. מחפש מישהי חכמה ומשעשעת.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m11.jpg",
  },
  {
    email: "yonatan@test.com",
    username: "yonatan",
    gender: "male",
    dateOfBirth: "1992-07-28",
    name: "יונתן",
    created: "2020-08-25",
    lastActive: "2026-01-14",
    description:
      "מורה לספורט עם תשוקה לכושר ולחיים בריאים. אוהב טבע, טיולים ואנרגיות חיוביות. מחפש מישהי פעילה ואופטימית.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/m12.jpg",
  },
  {
    email: "ben@test.com",
    username: "ben",
    gender: "male",
    dateOfBirth: "1988-11-05",
    name: "בן",
    created: "2020-09-10",
    lastActive: "2026-01-12",
    description:
      "אדריכל עם אהבה לעיצוב ואומנות. אני יצירתי, חושב מחוץ לקופסה ומחפש מישהי שמבינה את החזון שלי.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/m13.jpg",
  },
  {
    email: "noam@test.com",
    username: "noam",
    gender: "male",
    dateOfBirth: "1995-01-20",
    name: "נועם",
    created: "2020-09-28",
    lastActive: "2026-01-11",
    description:
      "סטודנט לרפואה עם חלום לעזור לאנשים. אוהב מוזיקה, קריאה וזמן איכות עם חברים. מחפש קשר אמיתי ועמוק.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m14.jpg",
  },
  {
    email: "roi@test.com",
    username: "roi",
    gender: "male",
    dateOfBirth: "1991-05-15",
    name: "רועי",
    created: "2020-10-12",
    lastActive: "2026-01-14",
    description:
      "עיתונאי עם סקרנות אינסופית. אוהב לחקור סיפורים, לפגוש אנשים ולגלות את העולם. מחפש מישהי חכמה ומעניינת.",
    city: "רמת גן",
    country: "ישראל",
    image: "/images/m15.jpg",
  },
  {
    email: "eyal@test.com",
    username: "eyal",
    gender: "male",
    dateOfBirth: "1989-08-22",
    name: "אייל",
    created: "2020-10-28",
    lastActive: "2026-01-13",
    description:
      "שף עם תשוקה לאוכל ולקולינריה. אני אוהב ליצור, לטעום ולחלוק חוויות. מחפש מישהי שאוהבת לאכול טוב.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/m16.jpg",
  },
  {
    email: "tal@test.com",
    username: "tal",
    gender: "male",
    dateOfBirth: "1993-12-01",
    name: "טל",
    created: "2020-11-10",
    lastActive: "2026-01-12",
    description:
      "מוזיקאי ומלחין. המוזיקה היא החיים שלי. אוהב להופיע, ליצור ולהשראות. מחפש מישהי שמבינה את הנשמה שלי.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m17.jpg",
  },
  {
    email: "omer@test.com",
    username: "omer",
    gender: "male",
    dateOfBirth: "1994-04-18",
    name: "עומר",
    created: "2020-11-25",
    lastActive: "2026-01-11",
    description:
      "מדען במחקר ביוטכנולוגיה. אני אנליטי, סקרן ואוהב לפתור בעיות. מחפש מישהי חכמה עם עומק.",
    city: "חיפה",
    country: "ישראל",
    image: "/images/m18.jpg",
  },
  {
    email: "asaf@test.com",
    username: "asaf",
    gender: "male",
    dateOfBirth: "1987-10-09",
    name: "אסף",
    created: "2020-12-08",
    lastActive: "2026-01-14",
    description:
      "יזם עם חזון גדול. אוהב אתגרים, סיכונים מחושבים והצלחה. מחפש מישהי שמאמינה בחלומות ותומכת בי.",
    city: "ירושלים",
    country: "ישראל",
    image: "/images/m19.jpg",
  },
  {
    email: "dan@test.com",
    username: "dan",
    gender: "male",
    dateOfBirth: "1996-02-26",
    name: "דן",
    created: "2020-12-20",
    lastActive: "2026-01-13",
    description:
      "מעצב UX/UI עם תשוקה לחוויית משתמש. אני יצירתי, פרפקציוניסט ואוהב פרטים. מחפש מישהי שמעריכה עיצוב.",
    city: "אילת",
    country: "ישראל",
    image: "/images/m20.jpg",
  },
  {
    email: "matan@test.com",
    username: "matan",
    gender: "male",
    dateOfBirth: "1990-06-14",
    name: "מתן",
    created: "2021-01-02",
    lastActive: "2026-01-12",
    description:
      "רואה חשבון עם יכולת לראות את התמונה הגדולה. אוהב סדר, תכנון ויציבות. מחפש קשר רציני ועתידי.",
    city: "חולון",
    country: "ישראל",
    image: "/images/m21.jpg",
  },
  {
    email: "yuval@test.com",
    username: "yuval",
    gender: "male",
    dateOfBirth: "1992-09-03",
    name: "יובל",
    created: "2021-01-18",
    lastActive: "2026-01-11",
    description:
      "מדריך טיולים עם אהבה לטבע ולהרפתקאות. אני חופשי, אוהב לגלות מקומות חדשים ולחוות. מחפש מישהי הרפתקנית.",
    city: "אשדוד",
    country: "ישראל",
    image: "/images/m22.jpg",
  },
  {
    email: "doron@test.com",
    username: "doron",
    gender: "male",
    dateOfBirth: "1986-12-21",
    name: "דורון",
    created: "2021-02-03",
    lastActive: "2026-01-14",
    description:
      "פסיכולוג עם רגישות ועומק. אוהב לשוחח, להקשיב ולהבין. מחפש מישהי עם אינטליגנציה רגשית גבוהה.",
    city: "תל אביב",
    country: "ישראל",
    image: "/images/m23.jpg",
  },
  {
    email: "itay@test.com",
    username: "itay",
    gender: "male",
    dateOfBirth: "1994-07-11",
    name: "איתי",
    created: "2021-02-16",
    lastActive: "2026-01-13",
    description:
      "צלם עם עין לפרטים ולרגעים מיוחדים. אוהב לתפוס את היופי בחיים. מחפש מישהי שאוהבת להיות מצולמת ומצלמת.",
    city: "רמת גן",
    country: "ישראל",
    image: "/images/m24.jpg",
  },
  {
    email: "nadav@test.com",
    username: "nadav",
    gender: "male",
    dateOfBirth: "1991-11-29",
    name: "נדב",
    created: "2021-03-01",
    lastActive: "2026-01-12",
    description:
      "עורך דין בתחום המסחרי. אני אנליטי, מדבר טוב ואוהב ויכוחים אינטלקטואליים. מחפש מישהי חדה וחכמה.",
    city: "נתניה",
    country: "ישראל",
    image: "/images/m25.jpg",
  },
];
